spring:
  application:
    name: Relay

  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

  datasource:
    url: jdbc:sqlserver://localhost:14330;databaseName=relay;encrypt=true;trustServerCertificate=true
    username: "sa"
    password: "${DB_PASSWORD}"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update       # dev only
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080